name: dart_api_query
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  dio: ^5.3.2
  weak_map: ^3.0.0

dev_dependencies:
  http_mock_adapter: ^0.4.4
  test: ^1.24.6
  very_good_analysis: ^5.0.0+1
