name: dart_api_query
description: Elegant and simple way to build requests for REST API.
version: 1.0.0
repository: https://github.com/luffynando/dart_api_query

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
dependencies:
  dio: ^5.3.2
  weak_map: ^3.0.0

dev_dependencies:
  http_mock_adapter: ^0.5.0
  test: ^1.24.6
  very_good_analysis: ^5.0.0+1
