name: dart_api_query
description: Elegant and simple way to build requests for REST API. If you use Laravel, matches with spatie/laravel-query-builder.
version: 1.1.2
homepage: https://github.com/luffynando/dart_api_query
repository: https://github.com/luffynando/dart_api_query
issue_tracker: https://github.com/luffynando/dart_api_query/issues

# This package supports all platforms listed below.
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

topics:
  - laravel
  - api
  - rest
  - query
  - builder

environment:
  sdk: ^3.0.6

dependencies:
  dio: ^5.4.3+1
  qs_dart: ^1.1.0
  weak_map: ^3.0.1

dev_dependencies:
  http_mock_adapter: ^0.6.1
  test: ^1.25.5
  very_good_analysis: ^5.1.0
